# Generated by Django 4.2.2 on 2023-06-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_mngmnt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='pName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='pTitle',
            new_name='title',
        ),
    ]
