# Generated by Django 4.2.3 on 2023-07-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mngmnt', '0012_userdetail_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
